name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ls -l
    - name: Run a multi-line script
      run: |
        cd gs-gradle-master/initial
        ls -l
        env
        chmod +x gradlew
        ./gradlew build
